force-app/main/default/objects/Cell_Color_Setting__mdt/Cell_Color_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Cell Color Setting</label>
    <pluralLabel>Cell Color Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cell_Color_Setting__mdt/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
                <default>true</default>
                <label>Red</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cell_Color_Setting__mdt/fields/Column_Setting__c.field-meta.xml
<CustomField>
    <fullName>Column_Setting__c</fullName>
    <label>Column Setting</label>
    <referenceTo>Column_Setting__mdt</referenceTo>
    <relationshipLabel>Cell Color Settings</relationshipLabel>
    <relationshipName>Cell_Color_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Cell_Color_Setting__mdt/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>less than</fullName>
                <default>true</default>
                <label>less than</label>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>equal to</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cell_Color_Setting__mdt/fields/Data_Value__c.field-meta.xml
<CustomField>
    <fullName>Data_Value__c</fullName>
    <label>Data Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Column_Setting__mdt/Column_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Column Setting</label>
    <pluralLabel>Column Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Column_Setting__mdt/fields/Datatable_Object_Setting__c.field-meta.xml
<CustomField>
    <fullName>Datatable_Object_Setting__c</fullName>
    <label>Datatable Object Setting</label>
    <referenceTo>Datatable_Object_Setting__mdt</referenceTo>
    <relationshipLabel>Column Settings</relationshipLabel>
    <relationshipName>Column_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Datatable_Object_Setting__mdt/Datatable_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Datatable Object Setting</label>
    <pluralLabel>Datatable Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/CellColorSettingController.cls
public with sharing class CellColorSettingController {

    public class DataTableObjectSetting {
        Id id;
        String name;
        String objectName;
        ColumnSetting[] columnSettings;
    }

    public class ColumnSetting {
        Id id;
        String name;
        String fieldAPIName;
        CellColorSetting[] cellColorSettings;
    }

    public class CellColorSetting {
        Id id;
        String name;
        String color;
        String condition;
        Integer dataValue;
    }

    @AuraEnabled (cacheable=true)
    public static String getDataTableObjectSettings(String ObjectSettingId){
        Id key = ObjectSettingId;
        Datatable_Object_Setting__mdt objectSettings =
        [SELECT Id, Object_Name__c, Label
        FROM Datatable_Object_Setting__mdt
        WHERE Id = :key];

        List<Column_Setting__mdt> columnSettings = [SELECT Id, Field_API_Name__c, Label, Datatable_Object_Setting__c
                                                   FROM Column_Setting__mdt
                                                   WHERE Datatable_Object_Setting__r.Id = :key];

        DataTableObjectSetting dataTableObjectSetting = new DataTableObjectSetting();
        dataTableObjectSetting.id = objectSettings.Id;
        dataTableObjectSetting.name = objectSettings.Label;
        dataTableObjectSetting.objectName = objectSettings.Object_Name__c;

        dataTableObjectSetting.columnSettings = new List<ColumnSetting>();

    for (Column_Setting__mdt columnSetting : columnSettings) {
        ColumnSetting newSetting = new ColumnSetting();
        newSetting.id = columnSetting.Id;
        newSetting.name = columnSetting.Label;
        newSetting.fieldAPIName = columnSetting.Field_API_Name__c;
        newSetting.cellColorSettings = new List<CellColorSetting>();

        List<Cell_Color_Setting__mdt> colorSettings = [SELECT Id, Label, Color__c, Condition__c, Data_Value__c
                                                       FROM Cell_Color_Setting__mdt
                                                       WHERE Column_Setting__r.Id =: columnSetting.id];
        
        for (Cell_Color_Setting__mdt colorSetting : colorSettings) {
            CellColorSetting newCellColorSetting = new CellColorSetting();
            newCellColorSetting.id = colorSetting.Id;
            newCellColorSetting.name = colorSetting.Label;
            newCellColorSetting.color = colorSetting.Color__c;
            newCellColorSetting.condition =colorSetting.Condition__c;
            newCellColorSetting.dataValue = Integer.valueOf(colorSetting.Data_Value__c);

           
            newSetting.cellColorSettings.add(newCellColorSetting);


            
        }
        dataTableObjectSetting.columnSettings.add(newSetting);
    }
    // System.debug(JSON.serialize(dataTableObjectSetting));
    return JSON.serialize(dataTableObjectSetting);  
    }
}