force-app/main/default/objects/Weather_Data__c/Weather_Data__c.object-meta.xml
<CustomObject>
    <label>Weather Data</label>
    <nameField>
        <label>Weather Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather_Data__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Weather_Data__c/fields/Wind_MPH__c.field-meta.xml
<CustomField>
    <fullName>Wind_MPH__c</fullName>
    <label>Wind MPH</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/weatherTest.cls
@isTest
public class weatherTest {
    @TestSetup
    
    static void makeData(){
        Weather_Data__c w = new Weather_Data__c(Name='Test Data', Humidity__c=70, Temperature__c=89, Wind_MPH__c=10);
        insert w;
    }
    @IsTest static void getWeatherData(){
        Test.startTest();
        Weather_Data__c query_data = [SELECT Id FROM Weather_Data__c WHERE Name = 'Test Data'];
        List<Weather_Data__c> weather = CsvController.getWeatherData();
        system.assert(weather.size() > 0, 'size should be greater than zero');
        Test.stopTest();
        
    } 
    
}